package com.notebook.customer.model;

import java.math.BigDecimal;

// Generated 2015-9-8 19:22:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * SysSelfcustomer generated by hbm2java
 * 客户-公司层面
 */
@Entity
@Table(name = "sys_selfcustomer")
public class BaseCustomer implements java.io.Serializable {

	private static final long serialVersionUID = -967224555515133782L;
	
	private String cusId;          //客户id
	private String cusName;        //客户名称
	private String cusCpname;      //公司名称
	private String cusCpename;     //公司英文名
	private String cusSex;         //客户性别
	private String cusPhone;       //客户电话
	private String cusEmail;       //邮箱地址
	private String cusDept;        //所属部门
	private String cusPesition;    //所属职位
	private String cusDesc;        //注册原因
	private Date creatTime;        //注册时间
	private Character cusFalg='0'; //状态
	private String cusReason;      //审核原因
	private String cusSynopsis;    //公司简介
	private String parUserId;      //审核人员id
	private String cusNumber;      //客户编号
	private String cusOrg;         //所属组织
	private Boolean isBlocked = false;//是否被冻结
	private Boolean blockopStatus = false;//冻结状态 0：冻结失败；1：冻结成功
	/**add by zengbo */
	private BigDecimal creditLines = new BigDecimal("0.000"); //信用额度
	private int expireKeepTime; //到期或欠费资源保留时长
	private Date overCreditTime; //欠费达信用额度时间
	/**add by zengbo end*/
	
	
	/**  add  by  chenglong*/
	private String cus_type;//客户类型  0：正式用户；1：合作客户；2：测试用户；3：公司自用客户；4：其他；
	/**   add by chenglong  end */
	
	
	public BaseCustomer() {
	}
	@Column(name= "cus_type",length = 1)
	public String getCus_type() {
		return cus_type;
	}

	public void setCus_type(String cus_type) {
		this.cus_type = cus_type;
	}

	public BaseCustomer(String cusId) {
		this.cusId = cusId;
	}
	
	/**
	 * 构造函数，用于查询customerDao.findAllCustomerName()
	 * @author zengbo
	 * @param cusId	客户ID
	 * @param cusName 客户名称
	 */
	public BaseCustomer(String cusId, String cusOrg){
		this.cusId = cusId;
		this.cusOrg = cusOrg;
	}
	@Id
	@GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "cus_id", unique = true, nullable = false, length = 32)
	public String getCusId() {
		return this.cusId;
	}

	public void setCusId(String cusId) {
		this.cusId = cusId;
	}

	@Column(name = "cus_name", length = 100)
	public String getCusName() {
		return this.cusName;
	}

	public void setCusName(String cusName) {
		this.cusName = cusName;
	}

	@Column(name = "cus_cpname",length = 100)
	public String getCusCpname() {
		return this.cusCpname;
	}

	public void setCusCpname(String cusCpname) {
		this.cusCpname = cusCpname;
	}

	@Column(name = "cus_cpename", length = 1)
	public String getCusCpename() {
		return this.cusCpename;
	}

	public void setCusCpename(String cusCpename) {
		this.cusCpename = cusCpename;
	}

	@Column(name = "cus_sex")
	public String getCusSex() {
		return this.cusSex;
	}

	public void setCusSex(String cusSex) {
		this.cusSex = cusSex;
	}

	@Column(name = "cus_phone")
	public String getCusPhone() {
		return this.cusPhone;
	}

	public void setCusPhone(String cusPhone) {
		this.cusPhone = cusPhone;
	}

	@Column(name = "cus_email")
	public String getCusEmail() {
		return this.cusEmail;
	}

	public void setCusEmail(String cusEmail) {
		this.cusEmail = cusEmail;
	}

	@Column(name = "cus_dept")
	public String getCusDept() {
		return this.cusDept;
	}

	public void setCusDept(String cusDept) {
		this.cusDept = cusDept;
	}

	@Column(name = "cus_pesition")
	public String getCusPesition() {
		return this.cusPesition;
	}

	public void setCusPesition(String cusPesition) {
		this.cusPesition = cusPesition;
	}

	@Column(name = "cus_desc")
	public String getCusDesc() {
		return this.cusDesc;
	}

	public void setCusDesc(String cusDesc) {
		this.cusDesc = cusDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creat_time", length = 19)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	@Column(name = "cus_falg", length = 1)
	public Character getCusFalg() {
		return this.cusFalg;
	}

	public void setCusFalg(Character cusFalg) {
		this.cusFalg = cusFalg;
	}

	@Column(name = "cus_reason", length = 2000)
	public String getCusReason() {
		return this.cusReason;
	}

	public void setCusReason(String cusReason) {
		this.cusReason = cusReason;
	}

	@Column(name = "cus_synopsis", length = 2000)
	public String getCusSynopsis() {
		return this.cusSynopsis;
	}

	public void setCusSynopsis(String cusSynopsis) {
		this.cusSynopsis = cusSynopsis;
	}

	@Column(name = "par_user_id", length = 32)
	public String getParUserId() {
		return this.parUserId;
	}

	public void setParUserId(String parUserId) {
		this.parUserId = parUserId;
	}

	@Column(name = "cus_number", length = 32)
	public String getCusNumber() {
		return this.cusNumber;
	}

	public void setCusNumber(String cusNumber) {
		this.cusNumber = cusNumber;
	}
	@Column(name = "cus_org", length = 32)
    public String getCusOrg() {
        return cusOrg;
    }

    public void setCusOrg(String cusOrg) {
        this.cusOrg = cusOrg;
    }
    @Column(name = "is_blocked")
	public Boolean getIsBlocked() {
		return isBlocked;
	}

	public void setIsBlocked(Boolean isBlocked) {
		this.isBlocked = isBlocked;
	}
	@Column(name = "block_opstatus")
	public Boolean getBlockopStatus() {
		return blockopStatus;
	}

	public void setBlockopStatus(Boolean blockopStatus) {
		this.blockopStatus = blockopStatus;
	}

	@Column(name = "credit_lines")
	public BigDecimal getCreditLines() {
		return creditLines;
	}

	public void setCreditLines(BigDecimal creditLines) {
		this.creditLines = creditLines;
	}

	@Column(name = "expire_keep_time")
	public int getExpireKeepTime() {
		return expireKeepTime;
	}

	public void setExpireKeepTime(int expireKeepTime) {
		this.expireKeepTime = expireKeepTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "over_credit_time", length=19)
	public Date getOverCreditTime() {
		return overCreditTime;
	}

	public void setOverCreditTime(Date overCreditTime) {
		this.overCreditTime = overCreditTime;
	}

	
}
